#! /bin/sh

#==========================================================
#
#   ██████╗  ██████╗██████╗  ██╗       ██╗███╗   ███╗
#   ██╔══██╗██╔════╝██╔══██╗ ██║  ██╗  ██║████╗ ████║
#   ██████╦╝╚█████╗ ██████╔╝ ╚██╗████╗██╔╝██╔████╔██║
#   ██╔══██╗ ╚═══██╗██╔═══╝   ████╔═████║ ██║╚██╔╝██║
#   ██████╦╝██████╔╝██║       ╚██╔╝ ╚██╔╝ ██║ ╚═╝ ██║
#   ╚═════╝ ╚═════╝ ╚═╝        ╚═╝   ╚═╝  ╚═╝     ╚═╝
#
#   Created by Ian Cox (Aerdian)
#   BSPWM configuration file for Atlas.
#   Information and support: https://aerdian.com/atlas-dotfiles
#   Last updated: 2020-12-24
#
#==========================================================

# Launch SXHKD and Polybar at start
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

# BSPWM colors
bspc config normal_border_color 	 "#2c363f"
bspc config active_border_color		 "#ffae34"
bspc config focused_border_color	 "#d2b365"
bspc config urgent_border_color		 "#dc6b7b"

# BSPWM configuration
bspc config border_width        	 2
bspc config window_gap          	 25
bspc config top_padding			 20

bspc config split_ratio         	 0.52
bspc config borderless_monocle  	 true
bspc config gapless_monocle     	 true

bspc config focus_follows_pointer	 false

# Monitor
bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X

# Hide Polybar in fullscreen
xdo lower -N "Polybar"
xdo above -N "Polybar" -t $(xdo id -N Bspwm -n root)

# Cursor settings
xsetroot -cursor_name left_ptr &

# EOF
